config:
  partial_parse: False
  send_anonymous_usage_stats: False

default:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: oauth
      project: "test-project"
      dataset: "dbt_default_dataset"
