name: Test
on:
  pull_request:
    paths-ignore:
      - "**/*.md"

jobs:
  test-fix:
    name: runner / sqlfluff (test-fix)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sqlfluff:
          - "3.0.7"
        extra_requirements_txt:
          - "testdata/test_failed_dbt/extra_requirements-1.6.txt"
        config:
          - ".sqlfluff.bigquery"
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: ${{ matrix.sqlfluff }}
          sqlfluff_command: fix
          templater: jinja
          working-directory: "${{ github.workspace }}/testdata/test_failed_dbt"
          config: "${{ github.workspace }}/testdata/test_failed_dbt/${{ matrix.config }}"
          paths: "${{ github.workspace }}/testdata/test_failed_dbt/models"
          extra_requirements_txt: "${{ github.workspace }}/${{ matrix.extra_requirements_txt }}"
          
  approve-action:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
       - run: echo "🎉 The approved was automatically triggered by a ${{ github.event_name }} event."
